service_name: mercury.infra
version: latest
register_ttl: 30s
register_interval: 15s
host: 0.0.0.0
port: 9600

log:
  # Log level(trace,debug,info,warn,error)
  mode: debug

config:
  passphrase: "la6YsO+bNX/+XIkO"
  path: "./.config"