// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthLevel int32

const (
	// AuthLevelNone is undefined/not authenticated
	AuthLevel_AuthLevelNone AuthLevel = 0
	// AuthLevelAnon is anonymous account/light authentication
	AuthLevel_AuthLevelAnon AuthLevel = 1
	// AuthLevelAuth is fully authenticated account
	AuthLevel_AuthLevelAuth AuthLevel = 2
	// AuthLevelRoot is a superuser
	AuthLevel_AuthLevelRoot AuthLevel = 3
)

var AuthLevel_name = map[int32]string{
	0: "AuthLevelNone",
	1: "AuthLevelAnon",
	2: "AuthLevelAuth",
	3: "AuthLevelRoot",
}

var AuthLevel_value = map[string]int32{
	"AuthLevelNone": 0,
	"AuthLevelAnon": 1,
	"AuthLevelAuth": 2,
	"AuthLevelRoot": 3,
}

func (x AuthLevel) String() string {
	return proto.EnumName(AuthLevel_name, int32(x))
}

func (AuthLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type UserState int32

const (
	UserState_UserStateNormal    UserState = 0
	UserState_UserStateSuspended UserState = 10
	UserState_UserStateDeleted   UserState = 20
	UserState_UserStateUndefined UserState = 30
)

var UserState_name = map[int32]string{
	0:  "UserStateNormal",
	10: "UserStateSuspended",
	20: "UserStateDeleted",
	30: "UserStateUndefined",
}

var UserState_value = map[string]int32{
	"UserStateNormal":    0,
	"UserStateSuspended": 10,
	"UserStateDeleted":   20,
	"UserStateUndefined": 30,
}

func (x UserState) String() string {
	return proto.EnumName(UserState_name, int32(x))
}

func (UserState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

type HandlerType int32

const (
	HandlerType_HandlerTypeToken HandlerType = 0
	HandlerType_HandlerTypeJWT   HandlerType = 1
)

var HandlerType_name = map[int32]string{
	0: "HandlerTypeToken",
	1: "HandlerTypeJWT",
}

var HandlerType_value = map[string]int32{
	"HandlerTypeToken": 0,
	"HandlerTypeJWT":   1,
}

func (x HandlerType) String() string {
	return proto.EnumName(HandlerType_name, int32(x))
}

func (HandlerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

// An authentication record.
type Record struct {
	// User UID
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Authentication level
	Level AuthLevel `protobuf:"varint,2,opt,name=level,proto3,enum=api.AuthLevel" json:"level,omitempty"`
	// Lifetime of this record
	Lifetime string `protobuf:"bytes,3,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	// User account state
	State                UserState `protobuf:"varint,4,opt,name=state,proto3,enum=api.UserState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Record) GetLevel() AuthLevel {
	if m != nil {
		return m.Level
	}
	return AuthLevel_AuthLevelNone
}

func (m *Record) GetLifetime() string {
	if m != nil {
		return m.Lifetime
	}
	return ""
}

func (m *Record) GetState() UserState {
	if m != nil {
		return m.State
	}
	return UserState_UserStateNormal
}

type GenerateTokenReq struct {
	HandlerType          HandlerType `protobuf:"varint,1,opt,name=handler_type,json=handlerType,proto3,enum=api.HandlerType" json:"handler_type,omitempty"`
	Record               *Record     `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenerateTokenReq) Reset()         { *m = GenerateTokenReq{} }
func (m *GenerateTokenReq) String() string { return proto.CompactTextString(m) }
func (*GenerateTokenReq) ProtoMessage()    {}
func (*GenerateTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *GenerateTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTokenReq.Unmarshal(m, b)
}
func (m *GenerateTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTokenReq.Marshal(b, m, deterministic)
}
func (m *GenerateTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTokenReq.Merge(m, src)
}
func (m *GenerateTokenReq) XXX_Size() int {
	return xxx_messageInfo_GenerateTokenReq.Size(m)
}
func (m *GenerateTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTokenReq proto.InternalMessageInfo

func (m *GenerateTokenReq) GetHandlerType() HandlerType {
	if m != nil {
		return m.HandlerType
	}
	return HandlerType_HandlerTypeToken
}

func (m *GenerateTokenReq) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type GenerateTokenResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateTokenResp) Reset()         { *m = GenerateTokenResp{} }
func (m *GenerateTokenResp) String() string { return proto.CompactTextString(m) }
func (*GenerateTokenResp) ProtoMessage()    {}
func (*GenerateTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *GenerateTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTokenResp.Unmarshal(m, b)
}
func (m *GenerateTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTokenResp.Marshal(b, m, deterministic)
}
func (m *GenerateTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTokenResp.Merge(m, src)
}
func (m *GenerateTokenResp) XXX_Size() int {
	return xxx_messageInfo_GenerateTokenResp.Size(m)
}
func (m *GenerateTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTokenResp proto.InternalMessageInfo

func (m *GenerateTokenResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthenticateReq struct {
	HandlerType          HandlerType `protobuf:"varint,1,opt,name=handler_type,json=handlerType,proto3,enum=api.HandlerType" json:"handler_type,omitempty"`
	Token                string      `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AuthenticateReq) Reset()         { *m = AuthenticateReq{} }
func (m *AuthenticateReq) String() string { return proto.CompactTextString(m) }
func (*AuthenticateReq) ProtoMessage()    {}
func (*AuthenticateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *AuthenticateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateReq.Unmarshal(m, b)
}
func (m *AuthenticateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateReq.Marshal(b, m, deterministic)
}
func (m *AuthenticateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateReq.Merge(m, src)
}
func (m *AuthenticateReq) XXX_Size() int {
	return xxx_messageInfo_AuthenticateReq.Size(m)
}
func (m *AuthenticateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateReq proto.InternalMessageInfo

func (m *AuthenticateReq) GetHandlerType() HandlerType {
	if m != nil {
		return m.HandlerType
	}
	return HandlerType_HandlerTypeToken
}

func (m *AuthenticateReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthenticateResp struct {
	Record               *Record  `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResp) Reset()         { *m = AuthenticateResp{} }
func (m *AuthenticateResp) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResp) ProtoMessage()    {}
func (*AuthenticateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *AuthenticateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResp.Unmarshal(m, b)
}
func (m *AuthenticateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResp.Marshal(b, m, deterministic)
}
func (m *AuthenticateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResp.Merge(m, src)
}
func (m *AuthenticateResp) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResp.Size(m)
}
func (m *AuthenticateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResp proto.InternalMessageInfo

func (m *AuthenticateResp) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.AuthLevel", AuthLevel_name, AuthLevel_value)
	proto.RegisterEnum("api.UserState", UserState_name, UserState_value)
	proto.RegisterEnum("api.HandlerType", HandlerType_name, HandlerType_value)
	proto.RegisterType((*Record)(nil), "api.Record")
	proto.RegisterType((*GenerateTokenReq)(nil), "api.GenerateTokenReq")
	proto.RegisterType((*GenerateTokenResp)(nil), "api.GenerateTokenResp")
	proto.RegisterType((*AuthenticateReq)(nil), "api.AuthenticateReq")
	proto.RegisterType((*AuthenticateResp)(nil), "api.AuthenticateResp")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0xf5, 0xda, 0x89, 0xa9, 0xc7, 0x89, 0x33, 0x99, 0x3a, 0xc1, 0xf8, 0x50, 0x82, 0xda, 0x43,
	0xea, 0x43, 0x0e, 0xca, 0x21, 0xa7, 0x42, 0x03, 0x85, 0x86, 0x52, 0x72, 0xd8, 0x38, 0xe4, 0x52,
	0x28, 0x6a, 0x76, 0x8c, 0x44, 0x95, 0xdd, 0xad, 0xb4, 0x2a, 0xe4, 0xda, 0x4b, 0x7f, 0xbb, 0xec,
	0x2a, 0x6c, 0xa5, 0xe0, 0x5e, 0x7a, 0xd3, 0x7b, 0xb3, 0xf3, 0x34, 0x6f, 0xde, 0x2e, 0x4c, 0x32,
	0x5b, 0x9c, 0xd9, 0xca, 0x38, 0x43, 0xa3, 0xcc, 0x16, 0xc9, 0x2f, 0x01, 0x63, 0xc9, 0xf7, 0xa6,
	0x52, 0x84, 0x30, 0x6a, 0x0a, 0xb5, 0x10, 0x27, 0xe2, 0x74, 0x22, 0xfd, 0x27, 0xbd, 0x81, 0xdd,
	0x92, 0x7f, 0x72, 0xb9, 0x18, 0x9e, 0x88, 0xd3, 0x59, 0x3a, 0x3b, 0xf3, 0xcd, 0x97, 0x8d, 0xcb,
	0x3f, 0x7b, 0x56, 0xb6, 0x45, 0x5a, 0xc2, 0x8b, 0xb2, 0xd8, 0xb0, 0x2b, 0x1e, 0x78, 0x31, 0x0a,
	0xcd, 0x11, 0x7b, 0x85, 0xda, 0x65, 0x8e, 0x17, 0x3b, 0x1d, 0x85, 0xdb, 0x9a, 0xab, 0x1b, 0xcf,
	0xca, 0xb6, 0x98, 0x94, 0x80, 0x1f, 0x59, 0x73, 0x95, 0x39, 0x5e, 0x9b, 0xef, 0xac, 0x25, 0xff,
	0xa0, 0x73, 0xd8, 0xcb, 0x33, 0xad, 0x4a, 0xae, 0xbe, 0xba, 0x47, 0xcb, 0x61, 0xac, 0x59, 0x8a,
	0x41, 0xe0, 0xaa, 0x2d, 0xac, 0x1f, 0x2d, 0xcb, 0x69, 0xfe, 0x17, 0xd0, 0x6b, 0x18, 0x57, 0xc1,
	0x4c, 0x98, 0x78, 0x9a, 0x4e, 0xc3, 0xf1, 0xd6, 0x9f, 0x7c, 0x2a, 0x25, 0x6f, 0xe1, 0xf0, 0xd9,
	0xdf, 0x6a, 0x4b, 0x73, 0xd8, 0x75, 0x1e, 0x3c, 0xd9, 0x6f, 0x41, 0xf2, 0x05, 0x0e, 0xbc, 0x5d,
	0xd6, 0xae, 0xb8, 0xf7, 0xf3, 0xfe, 0xef, 0x5c, 0x51, 0x7d, 0xd8, 0x55, 0xbf, 0x00, 0xec, 0xab,
	0xd7, 0xb6, 0xe3, 0x40, 0xfc, 0xd3, 0xc1, 0xea, 0x0e, 0x26, 0x31, 0x05, 0x3a, 0x84, 0xfd, 0x08,
	0xae, 0x8d, 0x66, 0x1c, 0xf4, 0xa8, 0x4b, 0x6d, 0x34, 0x8a, 0x3e, 0xd5, 0xb8, 0x1c, 0x87, 0x3d,
	0x4a, 0x1a, 0xe3, 0x70, 0xb4, 0xda, 0xc0, 0x24, 0x86, 0x43, 0x2f, 0xe1, 0x20, 0x82, 0x6b, 0x53,
	0x3d, 0x64, 0x25, 0x0e, 0xe8, 0x18, 0x28, 0x92, 0x37, 0x4d, 0x6d, 0x59, 0x2b, 0x56, 0x08, 0x34,
	0x07, 0x8c, 0xfc, 0x07, 0x2e, 0xd9, 0xb1, 0xc2, 0x79, 0xef, 0xf4, 0xad, 0x56, 0xbc, 0x29, 0x34,
	0x2b, 0x7c, 0xb5, 0xba, 0x80, 0xe9, 0x55, 0x6f, 0x3d, 0xd8, 0x81, 0x21, 0x14, 0x1c, 0x10, 0xc1,
	0xac, 0xc3, 0x7e, 0xba, 0x5b, 0xa3, 0x48, 0x7f, 0x0b, 0xd8, 0xf1, 0x43, 0xd3, 0x7b, 0xd8, 0xef,
	0x85, 0x48, 0x47, 0x61, 0x51, 0xcf, 0xaf, 0xd1, 0xf2, 0x78, 0x1b, 0x5d, 0xdb, 0x64, 0x40, 0xef,
	0x60, 0xaf, 0xbb, 0x7d, 0x9a, 0xc7, 0xdb, 0xdd, 0x89, 0x7b, 0x79, 0xb4, 0x85, 0xf5, 0xed, 0xdf,
	0xc6, 0xe1, 0x11, 0x9d, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x14, 0x91, 0x30, 0x2b, 0x51, 0x03,
	0x00, 0x00,
}
