// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendReq struct {
	// User UID
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// User Mobile
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendReq) Reset()         { *m = SendReq{} }
func (m *SendReq) String() string { return proto.CompactTextString(m) }
func (*SendReq) ProtoMessage()    {}
func (*SendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *SendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReq.Unmarshal(m, b)
}
func (m *SendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReq.Marshal(b, m, deterministic)
}
func (m *SendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReq.Merge(m, src)
}
func (m *SendReq) XXX_Size() int {
	return xxx_messageInfo_SendReq.Size(m)
}
func (m *SendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendReq proto.InternalMessageInfo

func (m *SendReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SendReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type SendResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResp) Reset()         { *m = SendResp{} }
func (m *SendResp) String() string { return proto.CompactTextString(m) }
func (*SendResp) ProtoMessage()    {}
func (*SendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *SendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResp.Unmarshal(m, b)
}
func (m *SendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResp.Marshal(b, m, deterministic)
}
func (m *SendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResp.Merge(m, src)
}
func (m *SendResp) XXX_Size() int {
	return xxx_messageInfo_SendResp.Size(m)
}
func (m *SendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendResp proto.InternalMessageInfo

type SendBatchReq struct {
	Uid                  []int64  `protobuf:"varint,1,rep,packed,name=uid,proto3" json:"uid,omitempty"`
	Mobiles              []string `protobuf:"bytes,2,rep,name=mobiles,proto3" json:"mobiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendBatchReq) Reset()         { *m = SendBatchReq{} }
func (m *SendBatchReq) String() string { return proto.CompactTextString(m) }
func (*SendBatchReq) ProtoMessage()    {}
func (*SendBatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *SendBatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendBatchReq.Unmarshal(m, b)
}
func (m *SendBatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendBatchReq.Marshal(b, m, deterministic)
}
func (m *SendBatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendBatchReq.Merge(m, src)
}
func (m *SendBatchReq) XXX_Size() int {
	return xxx_messageInfo_SendBatchReq.Size(m)
}
func (m *SendBatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendBatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendBatchReq proto.InternalMessageInfo

func (m *SendBatchReq) GetUid() []int64 {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *SendBatchReq) GetMobiles() []string {
	if m != nil {
		return m.Mobiles
	}
	return nil
}

type SendBatchResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendBatchResp) Reset()         { *m = SendBatchResp{} }
func (m *SendBatchResp) String() string { return proto.CompactTextString(m) }
func (*SendBatchResp) ProtoMessage()    {}
func (*SendBatchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *SendBatchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendBatchResp.Unmarshal(m, b)
}
func (m *SendBatchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendBatchResp.Marshal(b, m, deterministic)
}
func (m *SendBatchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendBatchResp.Merge(m, src)
}
func (m *SendBatchResp) XXX_Size() int {
	return xxx_messageInfo_SendBatchResp.Size(m)
}
func (m *SendBatchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendBatchResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendBatchResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendReq)(nil), "api.SendReq")
	proto.RegisterType((*SendResp)(nil), "api.SendResp")
	proto.RegisterType((*SendBatchReq)(nil), "api.SendBatchReq")
	proto.RegisterType((*SendBatchResp)(nil), "api.SendBatchResp")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x31, 0x0f, 0x82, 0x30,
	0x10, 0x85, 0x03, 0x35, 0x60, 0x2f, 0x10, 0xf5, 0x06, 0xd3, 0x30, 0x91, 0xba, 0x30, 0x31, 0xc0,
	0xe6, 0xe8, 0xee, 0x02, 0xbb, 0x09, 0x08, 0x89, 0x4d, 0x54, 0x4e, 0x8b, 0xff, 0xdf, 0x94, 0x02,
	0x41, 0xb7, 0xf7, 0xde, 0xe5, 0x7b, 0x79, 0x07, 0xbc, 0x22, 0x95, 0xd2, 0xbb, 0xeb, 0x3b, 0x64,
	0x15, 0x29, 0x99, 0x83, 0x5f, 0xb6, 0xcf, 0xa6, 0x68, 0x5f, 0xb8, 0x05, 0xf6, 0x51, 0x8d, 0x70,
	0x62, 0x27, 0xe1, 0x85, 0x91, 0xb8, 0x07, 0xef, 0xd1, 0xd5, 0xea, 0xde, 0x0a, 0x77, 0x08, 0x47,
	0x27, 0x01, 0xd6, 0x16, 0xd2, 0x24, 0x8f, 0x10, 0x18, 0x7d, 0xaa, 0xfa, 0xeb, 0xed, 0xa7, 0x85,
	0x25, 0xcc, 0xb6, 0x08, 0xf0, 0x2d, 0xa7, 0x85, 0x1b, 0xb3, 0x84, 0x17, 0x93, 0x95, 0x1b, 0x08,
	0x17, 0xac, 0xa6, 0xec, 0x02, 0xac, 0x3c, 0x97, 0x78, 0x80, 0x95, 0xc9, 0x31, 0x48, 0xcd, 0xda,
	0x71, 0x5f, 0x14, 0x2e, 0x9c, 0x26, 0xcc, 0x80, 0xcf, 0x30, 0xee, 0xe6, 0xdb, 0x34, 0x24, 0xc2,
	0xff, 0x48, 0x53, 0xed, 0x0d, 0x9f, 0xe7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x5d, 0xe7,
	0xfa, 0x06, 0x01, 0x00, 0x00,
}
